### ISSUE TITLE
리액트 쿼리에 관해 질문드립니다.

### ISSUE THREAD

**Issue by ubububububub** [ohah/react18-boilerplate#5]
안녕하세요 강사님 잘 지내셨을까요. 오랜만에 질문을 드리게 되었습니다.
저는 리액트 쿼리를 사용하면 서버 데이터를 클라이언트 데이터와 분리해서 사용해야 한다고 생각하고 있습니다. 그런데 다음과 같은 기능(별을 클릭하면 별과 평점을 수정할 수 있는)을 구현하여야 하는데 서버 데이터를 클라이언트에서 상태에 저장하여서 구현하는 방법도 될 것 같다고 생각하였습니다. 하지만 서버 데이터를 클라이언트 상태에 저장한다면 리액트 쿼리를 잘못 사용하고 있다고 생각이 들거든요. 리액트 쿼리를 사용할 때 서버 데이터를 클라이언트에 저장하여 상태로 관리하는 것은 무조건적으로  잘못된 것이 맞을까요?  강사님의 생각은 어떠신지 궁금해서 여쭈어 봅니다. 감사합니다.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/116259958/207385726-beeaba83-e448-40c1-80d7-28aefe904510.png">

**Comment by ohah** [comment]
https://react-query-v3.tanstack.com/plugins/persistQueryClient

리액트 쿼리에서도 로컬스토리지 저장하는 방법이 있기도하고,
기본적으로 리액트쿼리는 중복 요청을 막기 위해 데이터가 캐시됩니다.

리액트 쿼리의 기본설정값도 요청 된 데이터가 있고, 갱신해야할 이벤트가 아니라면 캐시 된 데이터를 보여주는 형태입니다
만약 해당 평점이 실시간으로 반영될 필요가 없고 한번 요청 이후 굳이 갱신할 필요가 없다면 로컬에서 저장하여 사용하셔도 무방하다고 생각됩니다

**Comment by ubububububub** [comment]
해당 기능은 실시간으로 반영이 필요한 데이터이고 사용자가 지속적으로 갱신할 수 있는 데이터입니다. 그럼 이 데이터는 로컬에 저장하지 않고 써야하는 것이네요. 아직 리액트 쿼리로 상태 관리하는 사고방식?이 익숙하지 않아서 헷갈리네요.  감사합니다.
